
name: Automation workflow

on:
  push:
    branches:
      - main
  

jobs:
  terraform:
    runs-on: self-hosted # Runs on your self-hosted runner instead of GitHub-hosted ones
   
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.My_Access_Key }}
          aws-secret-access-key: ${{ secrets.My_secret_Key}}
          aws-region: ap-south-1  # Change to your region
          audience: sts.amazonaws.com
    

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Initialize Terraform
        run: terraform init
      

      - name: Validate Terraform
        run: terraform validate
      - name: Import existing VPC from module
        run: |
         terraform state show module.vpc.aws_vpc.this || \
         terraform import module.vpc.aws_vpc.main vpc-0219578dc5af3223e
         
      - name: Terraform Apply Subnets (Targeted)
        run: terraform apply -auto-approve -target=module.vpc.aws_subnet.public -target=module.vpc.aws_subnet.private

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
